{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    release: kube-prometheus-stack # Required for the Terraform EKS Addon to discover it
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: {{ .Values.metrics.port }}
      path: {{ .Values.metrics.path }}
      interval: {{ .Values.metrics.interval }}
{{- end }}
